name: Release

on:
  push:
    tags:
      - 'v*'

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update manifest version for release
        run: |
          VERSION=$(echo "$GITHUB_REF_NAME" | sed 's/^v//')
          jq --arg ver "$VERSION" '.version = $ver | del(.version_name)' manifest.json > temp.json && mv temp.json manifest.json

      - name: Create Chrome Extension ZIP
        run: |
          zip -r firebase-user-changer-"$GITHUB_REF_NAME".zip . -x "*.git*" "*.github*"

      - name: Upload Workflow Artifact
        uses: actions/upload-artifact@v7
        with:
          name: firebase-user-changer-${{ github.ref_name }}
          path: firebase-user-changer-${{ github.ref_name }}.zip

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v3
        with:
          files: firebase-user-changer-${{ github.ref_name }}.zip
